version 0.95-4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1287,6 +1287,8 @@ if test "${with_libxml2+set}" = set; then
                     LIBXML2="-DLIBXML2=1";
                     USE_XML2="yes" ;
                  fi
+else
+  USE_XML2="maybe"
 fi;
 
 
@@ -2468,7 +2470,7 @@ if test -n "${USE_LIBXML}" ; then
        USE_XML2="yes"
        LIBXML2="-DLIBXML2=1";
     fi
-    echo "Used defined xml-config: ${XML_CONFIG}, XML Version: ${XML_VERSION}, XML2: ${USE_XML2}"
+    echo "User defined xml-config: ${XML_CONFIG}, XML Version: ${XML_VERSION}, XML2: ${USE_XML2}"
   fi
 
 
@@ -2478,7 +2480,7 @@ if test -n "${USE_LIBXML}" ; then
  if test -z "${LIBXML_INCDIR}" && test -z "${LIBXML_LIBDIR}" ; then
 
 
-  if test -n "${USE_XML2}" ; then
+     if test  "${USE_XML2}" == "yes" ; then
      if test -z "${XML_CONFIG}" ; then
        for ac_prog in xml2-config
 do
@@ -2531,7 +2533,7 @@ done
      fi
    fi
 
-   if test -z "${XML_CONFIG}" ; then
+         if test -z "${XML_CONFIG}" ; then
        for ac_prog in xml-config
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -2576,6 +2578,62 @@ fi
   test -n "$XML_CONFIG" && break
 done
 
+   fi
+
+
+  if test "${USE_XML2}" == "maybe" ; then
+     if test -z "${XML_CONFIG}" ; then
+       for ac_prog in xml2-config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XML_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XML_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XML_CONFIG="$XML_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XML_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+XML_CONFIG=$ac_cv_path_XML_CONFIG
+
+if test -n "$XML_CONFIG"; then
+  echo "$as_me:$LINENO: result: $XML_CONFIG" >&5
+echo "${ECHO_T}$XML_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$XML_CONFIG" && break
+done
+
+       if test -z "${XML_CONFIG}" ; then
+         echo "Cannot find xml2-config"
+         exit 1
+       else
+         echo "Using libxml version 2."
+       fi
+     fi
    fi
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -30,7 +30,7 @@ AC_ARG_WITH(libxml2,[  --with-libxml2    indicate that the libxml version is 2.0
                [ if test "${withval}" = yes; then
                     LIBXML2="-DLIBXML2=1";
                     USE_XML2="yes" ;
-                 fi])
+                 fi], USE_XML2="maybe")
 
 
 AC_ARG_WITH(xml-config,[  --with-xml-config    the name of the xml-config program to use.],
@@ -118,7 +118,7 @@ if test -n "${USE_LIBXML}" ; then
        USE_XML2="yes"
        LIBXML2="-DLIBXML2=1";
     fi
-    echo "Used defined xml-config: ${XML_CONFIG}, XML Version: ${XML_VERSION}, XML2: ${USE_XML2}"
+    echo "User defined xml-config: ${XML_CONFIG}, XML Version: ${XML_VERSION}, XML2: ${USE_XML2}"
   fi
 
 
@@ -132,7 +132,8 @@ if test -n "${USE_LIBXML}" ; then
 
     dnl find xml*-config 
 
-  if test -n "${USE_XML2}" ; then
+   dnl If they ask explicitly for xml2, find it or fail otherwise.
+  if test  "${USE_XML2}" == "yes" ; then
      if test -z "${XML_CONFIG}" ; then 
        AC_PATH_PROGS(XML_CONFIG, xml2-config)      
        if test -z "${XML_CONFIG}" ; then
@@ -142,8 +143,25 @@ if test -n "${USE_LIBXML}" ; then
      fi
    fi
 
+   dnl Otherwise, if they implicitly ask for xml-config
+   dnl find that.
    if test -z "${XML_CONFIG}" ; then
        AC_PATH_PROGS(XML_CONFIG, xml-config)
+   fi
+
+   dnl and if they don't have libxml version 1, see if they
+   dnl have libxml2 
+
+  if test "${USE_XML2}" == "maybe" ; then
+     if test -z "${XML_CONFIG}" ; then 
+       AC_PATH_PROGS(XML_CONFIG, xml2-config)      
+       if test -z "${XML_CONFIG}" ; then
+         echo "Cannot find xml2-config"
+         exit 1
+       else
+         echo "Using libxml version 2."
+       fi
+     fi
    fi
 
 
