version 0.95-3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP XML_CONFIG EGREP DUMP_WITH_ENCODING LIBXML2 LANGUAGE_DEFS LIBXML_INCDIR XMLPARSE_INCDIR PKG_LIBS PKG_CPPFLAGS SUPPORTS_LIBXML SUPPORTS_EXPAT LD_PATH SPLUS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP XML_CONFIG EGREP DUMP_WITH_ENCODING UNAME LIBXML2 LANGUAGE_DEFS LIBXML_INCDIR XMLPARSE_INCDIR PKG_LIBS PKG_CPPFLAGS SUPPORTS_LIBXML SUPPORTS_EXPAT LD_PATH SPLUS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1265,6 +1265,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 # Check whether --with-splus or --without-splus was given.
 if test "${with_splus+set}" = set; then
   withval="$with_splus"
@@ -1327,7 +1328,8 @@ fi;
 
 
 
- ac_ext=c
+
+  ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -2443,19 +2445,14 @@ if test -n "${USE_SPLUS}" ; then
  fi
 
    # Get the major version of the Splus being run.
- SPLUS_VERSION=`echo 'cat(version$major,"\n",sep="")' | ${SPLUS} | perl -e 'while(<STDIN>){ $x = $_;} printf $x;'`
-
+    SPLUS_VERSION=`echo 'cat(version$major,"\n",sep="")' | ${SPLUS} | perl -e 'while(<STDIN>){ $x = $_;} printf $x;'`
 
    # If this is version 3, we are in trouble.
  if test ${SPLUS_VERSION} -lt 5 ; then
     echo "This package does not work with SPlus 3, but only SPlus 5 and 6"
     exit 1
  fi
-
 fi  # end of USE_SPLUS.
-
-
-
 
 
 
@@ -2463,13 +2460,25 @@ fi  # end of USE_SPLUS.
 
 if test -n "${USE_LIBXML}" ; then
 
+     if test -n "${XML_CONFIG}" && test -x "${XML_CONFIG}" ; then
+    USING_USER_XML_CONFIG="yes"
+
+    XML_VERSION="`${XML_CONFIG} --version | sed -e 's/\..*//g'`"
+    if test "${XML_VERSION}" = "2" ; then
+       USE_XML2="yes"
+       LIBXML2="-DLIBXML2=1";
+    fi
+    echo "Used defined xml-config: ${XML_CONFIG}, XML Version: ${XML_VERSION}, XML2: ${USE_XML2}"
+  fi
+
+
   LANGUAGE_DEFS="${LANGUAGE_DEFS} -DHAVE_VALIDITY=1"
 
 
  if test -z "${LIBXML_INCDIR}" && test -z "${LIBXML_LIBDIR}" ; then
 
-   if test -n "${USE_XML2}" ; then
 
+  if test -n "${USE_XML2}" ; then
      if test -z "${XML_CONFIG}" ; then
        for ac_prog in xml2-config
 do
@@ -2522,7 +2531,7 @@ done
      fi
    fi
 
-     if test -z "${XML_CONFIG}" ; then
+   if test -z "${XML_CONFIG}" ; then
        for ac_prog in xml-config
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -2567,13 +2576,16 @@ fi
   test -n "$XML_CONFIG" && break
 done
 
-     fi
-
-     if test -n "${XML_CONFIG}" ; then
-       LIBXML_INCDIR=`${XML_CONFIG} --cflags | sed -e 's/-I//g'`
-       LIBXML_LIBDIR=`${XML_CONFIG} --libs`
-     fi
    fi
+
+
+
+   if test -n "${XML_CONFIG}" ; then
+       LIBXML_INCDIR=`${XML_CONFIG} --cflags`
+       LIBXML_LIBDIR=`${XML_CONFIG} --libs`
+       FOUND_LIBXML_INCLUDES="Ok"
+   fi
+  fi
 
 
 
@@ -2982,7 +2994,7 @@ fi
 
 
        if test -n "${FROM_LIBXML_DIR}" ; then
-         LIBXML_INCDIR="${dir}"
+         LIBXML_INCDIR="-I${dir}"
          CPPFLAGS="${TMP_CPPFLAGS} -I${dir} -I${dir}/libxml"
          PKG_CPPFLAGS="${TMP_CPPFLAGS} -I${dir} -I${dir}/libxml"
          echo "Found the libxml parser.h in $dir/libxml/"
@@ -3128,7 +3140,7 @@ fi
        if test -n "${FROM_GNOME_XML_DIR}" ; then
          PKG_CPPFLAGS="${PKG_CPPFLAGS} -DFROM_GNOME_XML_DIR=1"
          CPPFLAGS="${CPPFLAGS} -DFROM_GNOME_XML_DIR=1"
-         LIBXML_INCDIR="${dir}"
+         LIBXML_INCDIR="-I${dir}"
          echo "Found the gnome-xml parser in $dir"
          break
        fi
@@ -3289,8 +3301,8 @@ fi
 
 
   if test -z "${LIBXML2}" ; then
-CPPFLAGS="${PKG_CPPFLAGS} -I${LIBXML_INCDIR}"
-echo "${CPPFLAGS}"
+CPPFLAGS="${PKG_CPPFLAGS} ${LIBXML_INCDIR}"
+echo "Checking for 1.8: ${CPPFLAGS}"
   cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -3542,7 +3554,7 @@ fi
 
   PKG_CPPFLAGS="${PKG_CPPFLAGS} -DLIBXML"
   if test -z "${FROM_GNOME_XML_DIR}" ; then
-   PKG_CPPFLAGS="${PKG_CPPFLAGS} -I${LIBXML_INCDIR-.}"
+   PKG_CPPFLAGS="${PKG_CPPFLAGS} ${LIBXML_INCDIR--I.}"
   fi
 
 
@@ -4644,10 +4656,9 @@ fi
 
 if test -z "${USE_SPLUS}" ; then
 
-  LANGUAGE_DEFS="-DUSE_R=1 -D_R_=1"
-  PKG_SYS_FILE='system.file("scripts", name, pkg="RSPerl")'
+  LANGUAGE_DEFS="-DUSE_R=1 -D_R_=1 ${LANGUAGE_DEFS}"
 
-else  # so compiling for R.
+else
 
 
  if test ${SUPPORTS_LIBXML}="TRUE" ; then
@@ -4720,12 +4731,11 @@ fi
 
  fi # ? SUPPORTS_LIBXML = "TRUE"
 
- LANGUAGE_DEFS="-D_S_=1 -DUSE_S=1 -D_S4_=1 -D_SPLUS${SPLUS_VERSION}_ -DNO_SPLUS_THREAD_DEF=1"
+ LANGUAGE_DEFS="-D_S_=1 -DUSE_S=1 -D_S4_=1 -D_SPLUS${SPLUS_VERSION}_ -DNO_SPLUS_THREAD_DEF=1 ${LANGUAGE_DEFS}"
  INSTALL_DIR=`pwd`
  PKG_SYS_FILE="paste(\"${INSTALL_DIR}/inst/scripts/\", name,sep=\"\")"
 
 fi
-
 
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -4773,8 +4783,125 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 
+if test -n "LIBXML2" ; then
+
+TMP_CFLAGS="${CFLAGS}"
+CFLAGS="${CFLAGS} -pedantic-errors"
+echo "Checking for return type of xmlHashScan element routine."
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef FROM_GNOME_XML_DIR
+#include <gnome-xml/SAX.h>
+#include <gnome-xml/hash.h>
+#else
+#include <libxml/SAX.h>
+#include <libxml/hash.h>
+#endif
+
+int
+main ()
+{
+
+  void *(*foo)(void *, void *, xmlChar*);
+  xmlElementTablePtr table;
+  xmlHashScan(table, foo, NULL);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "xmlHashScan wants a return value."
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "No return value for xmlHashScan"; PKG_CPPFLAGS="${PKG_CPPFLAGS} -DNO_XML_HASH_SCANNER_RETURN=1"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+CFLAGS="${TMP_CFLAGS}"
+
+fi
+
+
+
+
+
 
 PKG_LIBS=${LIBS}
+
+
+
+if test -n "${NEED_XML_PARSER_ERROR}" ; then
+ # Extract the first word of "uname", so it can be a program name with args.
+set dummy uname; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_UNAME+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $UNAME in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_UNAME="$UNAME" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_UNAME="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+UNAME=$ac_cv_path_UNAME
+
+if test -n "$UNAME"; then
+  echo "$as_me:$LINENO: result: $UNAME" >&5
+echo "${ECHO_T}$UNAME" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+ if test -n "${UNAME}" ; then
+   host_os=`${UNAME}`
+   if test "${host_os}" = "Darwin" ; then
+     PKG_LIBS="-m $PKG_LIBS"
+   fi
+ fi
+fi
+
+
+
 
 
 
@@ -5459,6 +5586,7 @@ s,@CPP@,$CPP,;t t
 s,@XML_CONFIG@,$XML_CONFIG,;t t
 s,@EGREP@,$EGREP,;t t
 s,@DUMP_WITH_ENCODING@,$DUMP_WITH_ENCODING,;t t
+s,@UNAME@,$UNAME,;t t
 s,@LIBXML2@,$LIBXML2,;t t
 s,@LANGUAGE_DEFS@,$LANGUAGE_DEFS,;t t
 s,@LIBXML_INCDIR@,$LIBXML_INCDIR,;t t
@@ -5702,6 +5830,7 @@ if test "$no_create" != yes; then
 fi
 
 chmod +x cleanup
+
 
  if test -n "${USE_SPLUS}" ; then
  mv GNUmakefile.Splus GNUmakefile
